[package]
name = "treer-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "treer"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
futures-util.workspace = true
percent-encoding.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
treer-protocol = { path = "../treer-protocol" }
treer-transfer = { path = "../treer-transfer" }
url.workspace = true

[lints]
workspace = true
