[package]
name = "treer-agent-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strip-ansi-escapes.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
treer-agent-runtime = { path = "../treer-agent-runtime" }
treer-host-protocol = { path = "../treer-host-protocol" }
treer-protocol = { path = "../treer-protocol" }
treer-transfer = { path = "../treer-transfer" }
url.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink = "0.21.0"
tun2proxy = { version = "0.8.3", default-features = false }

[lints]
workspace = true
